# Livro para consulta:
- https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html
- https://jakevdp.github.io/PythonDataScienceHandbook/03.09-pivot-tables.html

# 1. Importando bibliotecas <a name="import"></a>

<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

# 2. Carregando o dataframe SINASC <a name="read"></a>
<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [2]:
sinasc_raw = pd.read_csv('SINASC_RO_2019.csv')
sinasc_raw.head()

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
0,1,2679477.0,110001,1,19,5.0,8 a 11 anos,NaN,0.0,0.0,...,5,1,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
1,1,2679477.0,110001,1,29,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,2,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
2,1,2679477.0,110001,1,37,9.0,8 a 11 anos,513205.0,2.0,0.0,...,5,3,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
3,1,2516500.0,110001,1,30,5.0,12 anos ou mais,231205.0,0.0,0.0,...,4,4,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia,-12.13178,-61.85308,397.0,3958.273
4,1,2516500.0,110001,1,30,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,5,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025

In [3]:
sinasc_raw.columns

Index(['ORIGEM', 'CODESTAB', 'CODMUNNASC', 'LOCNASC', 'IDADEMAE', 'ESTCIVMAE',
       'ESCMAE', 'CODOCUPMAE', 'QTDFILVIVO', 'QTDFILMORT', 'CODMUNRES',
       'GESTACAO', 'GRAVIDEZ', 'PARTO', 'CONSULTAS', 'DTNASC', 'HORANASC',
       'SEXO', 'APGAR1', 'APGAR5', 'RACACOR', 'PESO', 'IDANOMAL', 'DTCADASTRO',
       'CODANOMAL', 'NUMEROLOTE', 'VERSAOSIST', 'DTRECEBIM', 'DIFDATA',
       'DTRECORIGA', 'NATURALMAE', 'CODMUNNATU', 'CODUFNATU', 'ESCMAE2010',
       'SERIESCMAE', 'DTNASCMAE', 'RACACORMAE', 'QTDGESTANT', 'QTDPARTNOR',
       'QTDPARTCES', 'IDADEPAI', 'DTULTMENST', 'SEMAGESTAC', 'TPMETESTIM',
       'CONSPRENAT', 'MESPRENAT', 'TPAPRESENT', 'STTRABPART', 'STCESPARTO',
       'TPNASCASSI', 'TPFUNCRESP', 'TPDOCRESP', 'DTDECLARAC', 'ESCMAEAGR1',
       'STDNEPIDEM', 'STDNNOVA', 'CODPAISRES', 'TPROBSON', 'PARIDADE',
       'KOTELCHUCK', 'CONTADOR', 'munResStatus', 'munResTipo', 'munResNome',
       'munResUf', 'munResLat', 'munResLon', 'munResAlt', 'munResArea'],
      dtype='object')

# Tarefa 2

### 1. Crie 2 faixas de Latitude do município (munResLat) sendo uma acima e outra abaixo de -10.5 e aplique o groupby usando essas faixas como chave e realize operações de soma, media, minimo, maximo, mediana, desvio padrao, variancia pra pelo menos 2 variáveis numéricas ainda não utilizadas

In [5]:
# Create a new column for latitude ranges
sinasc_raw['LatRange'] = pd.cut(sinasc_raw['munResLat'], bins=[sinasc_raw['munResLat'].min(), -10.5, sinasc_raw['munResLat'].max()], labels=['Acima -10.5', 'Abaixo -10.5'])

# Perform the groupby operation
grouped_data = sinasc_raw.groupby('LatRange').agg({'PESO': ['sum', 'mean', 'min', 'max', 'median', 'std', 'var'],
                                                   'IDADEMAE': ['sum', 'mean', 'min', 'max', 'median', 'std', 'var']})

grouped_data

                  PESO                                              \
                   sum         mean  min   max  median         std
LatRange
Acima -10.5   41831706  3239.503291  258  5985  3270.0  532.148867
Abaixo -10.5  45555148  3246.055864  295  5190  3275.0  556.487709

                            IDADEMAE                                      \
                        var      sum       mean min max median       std
LatRange
Acima -10.5   283182.416830   338060  26.179819  12  53   26.0  6.321275
Abaixo -10.5  309678.570242   365094  26.014964  11  52   25.0  6.447663


                    var
LatRange
Acima -10.5   39.958524
Abaixo -10.5  41.572355

### 2. Crie 2 faixas da área dos municípios (munResArea) sendo uma acima e outra abaixo de 3000 e aplique o groupby usando essas faixas como chave e realize operações de soma, media, minimo, maximo, mediana, desvio padrao, variancia pra pelo menos 2 variáveis numéricas ainda não utilizadas

In [7]:
# Create a new column for area ranges
sinasc_raw['AreaRange'] = pd.cut(sinasc_raw['munResArea'], bins=[sinasc_raw['munResArea'].min(), 3000, sinasc_raw['munResArea'].max()], labels=['Abaixo 3000', 'Acima 3000'])

# Perform the groupby operation
grouped_data_area = sinasc_raw.groupby('AreaRange').agg({'APGAR1': ['sum', 'mean', 'min', 'max', 'median', 'std', 'var'],
                                                         'APGAR5': ['sum', 'mean', 'min', 'max', 'median', 'std', 'var']})

grouped_data_area

               APGAR1                                                  \
                  sum      mean  min   max median       std       var
AreaRange
Abaixo 3000   41558.0  8.074218  0.0  10.0    8.0  1.009443  1.018976
Acima 3000   177079.0  8.152808  0.0  10.0    8.0  0.978517  0.957495

               APGAR5
                  sum      mean  min   max median       std       var
AreaRange
Abaixo 3000   46982.0  9.131584  0.0  10.0    9.0  0.801427  0.642286
Acima 3000   199579.0  9.190836  0.0  10.0    9.0  0.787591  0.620299

### 3. Determine faixas na variável munResAlt e aplique o groupby usando essas faixas como chave e realize operações de soma, media, minimo, maximo, mediana, desvio padrao, variancia pra pelo menos 2 variáveis numéricas ainda não utilizadas

In [8]:
sinasc_raw['munResAlt'].describe()

count    27027.000000
mean       179.111999
std        123.138365
min         85.000000
25%         87.000000
50%        153.000000
75%        191.000000
max        595.000000
Name: munResAlt, dtype: float64

In [12]:
# Create a new column for altitude ranges
sinasc_raw['Altitude'] = pd.cut(sinasc_raw['munResAlt'], bins=[85, 153, 191, 595], labels=['Baixa', 'Média', 'Alta'])

# Perform the groupby operation
grouped_data_alt = sinasc_raw.groupby('Altitude').agg({'QTDFILVIVO': ['sum', 'mean', 'min', 'max', 'median', 'std', 'var'],
                                                       'QTDFILMORT': ['sum', 'mean', 'min', 'max', 'median', 'std', 'var']})

grouped_data_alt

         QTDFILVIVO                                                  \
                sum      mean  min   max median       std       var
Altitude
Baixa       13973.0  1.175684  0.0  14.0    1.0  1.260605  1.589126
Média        6354.0  0.922608  0.0   9.0    1.0  1.041525  1.084773
Alta         6066.0  0.950784  0.0  30.0    1.0  1.079861  1.166099

         QTDFILMORT
                sum      mean  min   max median       std       var
Altitude
Baixa        3429.0  0.300289  0.0   9.0    0.0  0.642765  0.413147
Média        1585.0  0.230949  0.0   5.0    0.0  0.534301  0.285477
Alta         1538.0  0.242281  0.0  28.0    0.0  0.638724  0.407968

### 4. Plote no mesmo grafico ao longo do tempo a idade media das mulheres de cada regiao imediatas de rondonia
https://pt.wikipedia.org/wiki/Lista_de_regi%C3%B5es_geogr%C3%A1ficas_intermedi%C3%A1rias_e_imediatas_de_Rond%C3%B4nia

In [ ]:
#Entendi como utilizar os dados do Wikipedia para subdividir em regiões
#Não entendi exatamente "Plote no mesmo gráfico ao longo do tempo", quais as variáveis necessárias para esse exercício

### 5. Utilize a tabela do link abaixo e crie faixas utilizando o mapping e gere agrupamentos utilizando essas faixas como chave

### 5.1 IDH
A - https://pt.wikipedia.org/wiki/Lista_de_munic%C3%ADpios_de_Rond%C3%B4nia_por_IDH-M

In [22]:
import pandas as pd

# Dados dos municípios e seus respectivos IDHs
data = {
    'Municipio': [
        "Porto Velho", "Vilhena", "Cacoal", "Ji-Paraná", "Pimenta Bueno", "Ariquemes", "Rolim de Moura", "Cerejeiras", "Jaru", 
        "Colorado do Oeste", "Ouro Preto do Oeste", "Espigão d'Oeste", "Santa Luzia d'Oeste", "Pimenteiras do Oeste", "Presidente Médici", 
        "Castanheiras", "Guajará-Mirim", "Chupinguaia", "Cabixi", "Candeias do Jamari", "São Felipe d'Oeste", "Cacaulândia", 
        "São Miguel do Guaporé", "Mirante da Serra", "Alvorada d'Oeste", "Teixeirópolis", "Nova Brasilândia d'Oeste", "Rio Crespo", 
        "Primavera de Rondônia", "Alta Floresta d'Oeste", "Ministro Andreazza", "Novo Horizonte do Oeste", "Vale do Paraíso", 
        "Alto Paraíso", "Parecis", "Buritis", "Itapuã do Oeste", "Corumbiara", "Cujubim", "Costa Marques", "São Francisco do Guaporé", 
        "Urupá", "Monte Negro", "Seringueiras", "Governador Jorge Teixeira", "Machadinho d'Oeste", "Campo Novo de Rondônia", 
        "Alto Alegre dos Parecis", "Theobroma", "Nova União", "Nova Mamoré", "Vale do Anari"
    ],
    'IDH': [
        0.736, 0.731, 0.718, 0.714, 0.710, 0.702, 0.700, 0.692, 0.689, 
        0.685, 0.682, 0.672, 0.670, 0.665, 0.664, 
        0.658, 0.657, 0.652, 0.650, 0.649, 0.649, 0.646, 
        0.646, 0.643, 0.643, 0.643, 0.643, 0.643, 
        0.641, 0.641, 0.638, 0.634, 0.627, 
        0.625, 0.617, 0.616, 0.614, 0.613, 0.612, 0.611, 0.611, 
        0.609, 0.607, 0.598, 0.596, 0.596, 0.593, 
        0.592, 0.589, 0.587, 0.587, 0.584
    ]
}

# Criação do DataFrame
df = pd.DataFrame(data)

# Definição das faixas de IDH
bins = [0, 0.499, 0.599, 0.699, 0.799, 1]
labels = ['IDH-M muito baixo', 'IDH-M baixo', 'IDH-M médio', 'IDH-M alto', 'IDH-M muito alto']

# Criação da coluna 'Faixa_IDH' com base no mapping
df['Faixa_IDH'] = pd.cut(df['IDH'], bins=bins, labels=labels)

# Agrupando o dataframe pela coluna 'Faixa_IDH'
df_grouped = df.groupby('Faixa_IDH')

df_grouped.groups

{'IDH-M muito baixo': [], 'IDH-M baixo': [43, 44, 45, 46, 47, 48, 49, 50, 51], 'IDH-M médio': [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42], 'IDH-M alto': [0, 1, 2, 3, 4, 5, 6], 'IDH-M muito alto': []}

In [25]:
df_grouped.describe()

                    IDH                                                    \
                  count      mean       std    min    25%    50%      75%
Faixa_IDH
IDH-M muito baixo   0.0       NaN       NaN    NaN    NaN    NaN      NaN
IDH-M baixo         9.0  0.591333  0.004848  0.584  0.587  0.592  0.59600
IDH-M médio        36.0  0.643250  0.024046  0.607  0.623  0.643  0.65725
IDH-M alto          7.0  0.715857  0.013668  0.700  0.706  0.714  0.72450
IDH-M muito alto    0.0       NaN       NaN    NaN    NaN    NaN      NaN


                     max
Faixa_IDH
IDH-M muito baixo    NaN
IDH-M baixo        0.598
IDH-M médio        0.692
IDH-M alto         0.736
IDH-M muito alto     NaN

In [27]:

df_grouped.head()

                    Municipio    IDH    Faixa_IDH
0                 Porto Velho  0.736   IDH-M alto
1                     Vilhena  0.731   IDH-M alto
2                      Cacoal  0.718   IDH-M alto
3                   Ji-Paraná  0.714   IDH-M alto
4               Pimenta Bueno  0.710   IDH-M alto
7                  Cerejeiras  0.692  IDH-M médio
8                        Jaru  0.689  IDH-M médio
9           Colorado do Oeste  0.685  IDH-M médio
10        Ouro Preto do Oeste  0.682  IDH-M médio
11            Espigão d'Oeste  0.672  IDH-M médio
43               Seringueiras  0.598  IDH-M baixo
44  Governador Jorge Teixeira  0.596  IDH-M baixo
45         Machadinho d'Oeste  0.596  IDH-M baixo
46     Campo Novo de Rondônia  0.593  IDH-M baixo
47    Alto Alegre dos Parecis  0.592  IDH-M baixo

### 5.2 IFDM 
B - https://pt.wikipedia.org/wiki/Lista_de_munic%C3%ADpios_de_Rond%C3%B4nia_por_IFDM

In [28]:
# Dados dos municípios e seus respectivos IFDMs
data_ifdm = {
    'Municipio': [
        "Ariquemes", "Vilhena", "Pimenta Bueno", "Porto Velho", "Ji-Paraná", "Cacoal", "Santa Luzia d'Oeste", "Rolim de Moura", "Chupinguaia", 
        "São Miguel do Guaporé", "Pimenteiras do Oeste", "Teixeirópolis", "Colorado do Oeste", "Jaru", "Rio Crespo", 
        "Primavera de Rondônia", "Alta Floresta d'Oeste", "Ouro Preto do Oeste", "São Francisco do Guaporé", "Candeias do Jamari", "Buritis", 
        "São Felipe d'Oeste", "Presidente Médici", "Cerejeiras", "Monte Negro", "Urupá", "Espigão d'Oeste", "Seringueiras", "Alvorada d'Oeste", 
        "Itapuã do Oeste", "Cabixi", "Novo Horizonte do Oeste", "Nova Brasilândia d'Oeste", "Vale do Paraíso", "Corumbiara", "Alto Paraíso", 
        "Cacaulândia", "Vale do Anari", "Ministro Andreazza", "Costa Marques", "Nova União", "Guajará-Mirim", "Mirante da Serra", "Parecis", 
        "Castanheiras", "Theobroma", "Machadinho d'Oeste", "Campo Novo de Rondônia", "Nova Mamoré", "Cujubim", "Alto Alegre dos Parecis", 
        "Governador Jorge Teixeira"
    ],
    'IFDM': [
        0.7746, 0.7465, 0.7383, 0.7257, 0.7117, 0.7111, 0.6850, 0.6785, 0.6766, 
        0.6699, 0.6501, 0.6500, 0.6473, 0.6450, 0.6430, 
        0.6384, 0.6337, 0.6261, 0.6214, 0.6199, 0.6153, 0.6153, 
        0.6140, 0.6137, 0.6016, 0.6006, 0.5973, 0.5922, 0.5919, 
        0.5903, 0.5887, 0.5858, 0.5857, 0.5818, 0.5759, 0.5735, 
        0.5721, 0.5710, 0.5657, 0.5626, 0.5571, 0.5541, 0.5519, 0.5502, 
        0.5430, 0.5405, 0.5322, 0.5272, 0.5084, 0.5055, 0.5046, 0.4562
    ]
}

# Criação do DataFrame
df_ifdm = pd.DataFrame(data_ifdm)

# Definição das faixas de IFDM
bins_ifdm = [0, 0.4, 0.6, 0.8, 1]
labels_ifdm = ['Desenvolvimento baixo', 'Desenvolvimento regular', 'Desenvolvimento moderado', 'Desenvolvimento alto']

# Criação da coluna 'Faixa_IFDM' com base no mapping
df_ifdm['Faixa_IFDM'] = pd.cut(df_ifdm['IFDM'], bins=bins_ifdm, labels=labels_ifdm)

# Agrupando o dataframe pela coluna 'Faixa_IFDM'
df_ifdm_grouped = df_ifdm.groupby('Faixa_IFDM')

df_ifdm_grouped.groups

{'Desenvolvimento baixo': [], 'Desenvolvimento regular': [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51], 'Desenvolvimento moderado': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25], 'Desenvolvimento alto': []}

In [29]:
df_ifdm_grouped.head()

           Municipio    IFDM                Faixa_IFDM
0          Ariquemes  0.7746  Desenvolvimento moderado
1            Vilhena  0.7465  Desenvolvimento moderado
2      Pimenta Bueno  0.7383  Desenvolvimento moderado
3        Porto Velho  0.7257  Desenvolvimento moderado
4          Ji-Paraná  0.7117  Desenvolvimento moderado
26   Espigão d'Oeste  0.5973   Desenvolvimento regular
27      Seringueiras  0.5922   Desenvolvimento regular
28  Alvorada d'Oeste  0.5919   Desenvolvimento regular
29   Itapuã do Oeste  0.5903   Desenvolvimento regular
30            Cabixi  0.5887   Desenvolvimento regular

### 5.3 PIB
C - https://pt.wikipedia.org/wiki/Lista_de_munic%C3%ADpios_de_Rond%C3%B4nia_por_PIB

In [30]:
import pandas as pd

# Dados fornecidos
municipios = ["Porto Velho", "Ji-Paraná", "Vilhena", "Ariquemes", "Cacoal", "Jaru", 
              "Rolim de Moura", "Pimenta Bueno", "Guajará-Mirim", "Ouro Preto do Oeste", 
              "Buritis", "Machadinho do Oeste", "Espigão d'Oeste", "São Miguel do Guaporé", 
              "Candeias do Jamari", "Nova Mamoré", "Cerejeiras", "Alta Floresta do Oeste", 
              "Presidente Médici", "Cujubim", "Nova Brasilândia do Oeste", "Alto Paraíso", 
              "São Francisco do Guaporé", "Colorado do Oeste", "Monte Negro", 
              "Alto Alegre dos Parecis", "Campo Novo de Rondônia", "Alvorada do Oeste", 
              "Chupinguaia", "Corumbiara", "Ministro Andreazza", "Urupá", "Costa Marques", 
              "Seringueiras", "Mirante da Serra", "Governador Jorge Teixeira", "Theobroma", 
              "Santa Luzia do Oeste", "Novo Horizonte do Oeste", "Itapuã do Oeste", 
              "Vale do Paraíso", "Cacaulândia", "Cabixi", "Vale do Anari", "Nova União", 
              "Parecis", "Rio Crespo", "Pimenteiras do Oeste", "Teixeirópolis", 
              "São Felipe do Oeste", "Castanheiras", "Primavera de Rondônia"]

pibs = [17912.070, 3783.972, 2831.175, 2579.830, 2261.644, 1500.890, 
        1283.434, 1164.877, 893, 834, 726, 633, 625, 616, 548, 529, 
        507, 496, 428, 385, 360, 358, 353, 335, 219.152, 213.410, 
        208.821, 204.098, 190.331, 188.218, 174.633, 172.143, 171.878, 
        169.429, 163.955, 148.027, 140.601, 135.934, 129.399, 129.351, 
        116.742, 116.635, 113.031, 105.208, 92.346, 80.759, 76.854, 
        76.756, 72.089, 72.084, 59.779, 52.908]

# Criando o DataFrame
df = pd.DataFrame({
    'Municipio': municipios,
    'PIB (milhões de R$)': pibs
})

df

                    Municipio  PIB (milhões de R$)
0                 Porto Velho            17912.070
1                   Ji-Paraná             3783.972
2                     Vilhena             2831.175
3                   Ariquemes             2579.830
4                      Cacoal             2261.644
5                        Jaru             1500.890
6              Rolim de Moura             1283.434
7               Pimenta Bueno             1164.877
8               Guajará-Mirim              893.000
9         Ouro Preto do Oeste              834.000
10                    Buritis              726.000
11        Machadinho do Oeste              633.000
12            Espigão d'Oeste              625.000
13      São Miguel do Guaporé              616.000
14         Candeias do Jamari              548.000
15                Nova Mamoré              529.000
16                 Cerejeiras              507.000
17     Alta Floresta do Oeste              496.000
18          Presidente Médici              428.000
19                    Cujubim              385.000
20  Nova Brasilândia do Oeste              360.000
21               Alto Paraíso              358.000
22   São Francisco do Guaporé              353.000
23          Colorado do Oeste              335.000
24                Monte Negro              219.152
25    Alto Alegre dos Parecis              213.410
26     Campo Novo de Rondônia              208.821
27          Alvorada do Oeste              204.098
28                Chupinguaia              190.331
29                 Corumbiara              188.218
30         Ministro Andreazza              174.633
31                      Urupá              172.143
32              Costa Marques              171.878
33               Seringueiras              169.429
34           Mirante da Serra              163.955
35  Governador Jorge Teixeira              148.027
36                  Theobroma              140.601
37       Santa Luzia do Oeste              135.934
38    Novo Horizonte do Oeste              129.399
39            Itapuã do Oeste              129.351
40            Vale do Paraíso              116.742
41                Cacaulândia              116.635
42                     Cabixi              113.031
43              Vale do Anari              105.208
44                 Nova União               92.346
45                    Parecis               80.759
46                 Rio Crespo               76.854
47       Pimenteiras do Oeste               76.756
48              Teixeirópolis               72.089
49        São Felipe do Oeste               72.084
50               Castanheiras               59.779
51      Primavera de Rondônia               52.908

In [31]:
# Definindo as faixas de PIB
bins = [0, 100, 200, 300, 500, 1000, float('inf')]

# Definindo os rótulos para as faixas
labels = ['Até 100 Milhões', 'Acima de 100 Milhões', 'Acima de 200 Milhões', 
          'Acima de 300 Milhões', 'Acima de 500 Milhões', 'Acima de 1 Bilhão']

# Criando a coluna de agrupamento
df['Faixa PIB'] = pd.cut(df['PIB (milhões de R$)'], bins=bins, labels=labels)

df

                    Municipio  PIB (milhões de R$)             Faixa PIB
0                 Porto Velho            17912.070     Acima de 1 Bilhão
1                   Ji-Paraná             3783.972     Acima de 1 Bilhão
2                     Vilhena             2831.175     Acima de 1 Bilhão
3                   Ariquemes             2579.830     Acima de 1 Bilhão
4                      Cacoal             2261.644     Acima de 1 Bilhão
5                        Jaru             1500.890     Acima de 1 Bilhão
6              Rolim de Moura             1283.434     Acima de 1 Bilhão
7               Pimenta Bueno             1164.877     Acima de 1 Bilhão
8               Guajará-Mirim              893.000  Acima de 500 Milhões
9         Ouro Preto do Oeste              834.000  Acima de 500 Milhões
10                    Buritis              726.000  Acima de 500 Milhões
11        Machadinho do Oeste              633.000  Acima de 500 Milhões
12            Espigão d'Oeste              625.000  Acima de 500 Milhões
13      São Miguel do Guaporé              616.000  Acima de 500 Milhões
14         Candeias do Jamari              548.000  Acima de 500 Milhões
15                Nova Mamoré              529.000  Acima de 500 Milhões
16                 Cerejeiras              507.000  Acima de 500 Milhões
17     Alta Floresta do Oeste              496.000  Acima de 300 Milhões
18          Presidente Médici              428.000  Acima de 300 Milhões
19                    Cujubim              385.000  Acima de 300 Milhões
20  Nova Brasilândia do Oeste              360.000  Acima de 300 Milhões
21               Alto Paraíso              358.000  Acima de 300 Milhões
22   São Francisco do Guaporé              353.000  Acima de 300 Milhões
23          Colorado do Oeste              335.000  Acima de 300 Milhões
24                Monte Negro              219.152  Acima de 200 Milhões
25    Alto Alegre dos Parecis              213.410  Acima de 200 Milhões
26     Campo Novo de Rondônia              208.821  Acima de 200 Milhões
27          Alvorada do Oeste              204.098  Acima de 200 Milhões
28                Chupinguaia              190.331  Acima de 100 Milhões
29                 Corumbiara              188.218  Acima de 100 Milhões
30         Ministro Andreazza              174.633  Acima de 100 Milhões
31                      Urupá              172.143  Acima de 100 Milhões
32              Costa Marques              171.878  Acima de 100 Milhões
33               Seringueiras              169.429  Acima de 100 Milhões
34           Mirante da Serra              163.955  Acima de 100 Milhões
35  Governador Jorge Teixeira              148.027  Acima de 100 Milhões
36                  Theobroma              140.601  Acima de 100 Milhões
37       Santa Luzia do Oeste              135.934  Acima de 100 Milhões
38    Novo Horizonte do Oeste              129.399  Acima de 100 Milhões
39            Itapuã do Oeste              129.351  Acima de 100 Milhões
40            Vale do Paraíso              116.742  Acima de 100 Milhões
41                Cacaulândia              116.635  Acima de 100 Milhões
42                     Cabixi              113.031  Acima de 100 Milhões
43              Vale do Anari              105.208  Acima de 100 Milhões
44                 Nova União               92.346       Até 100 Milhões
45                    Parecis               80.759       Até 100 Milhões
46                 Rio Crespo               76.854       Até 100 Milhões
47       Pimenteiras do Oeste               76.756       Até 100 Milhões
48              Teixeirópolis               72.089       Até 100 Milhões
49        São Felipe do Oeste               72.084       Até 100 Milhões
50               Castanheiras               59.779       Até 100 Milhões
51      Primavera de Rondônia               52.908       Até 100 Milhões

### Analise as respostas encontradas, tire algum insight delas, conte pra gente algo encontrado nos dados.

Exemplo:
- Ah, descobri que a idade mediana das mulheres que deram a luz no ano de 2019 dos municipios com o PIB mais alto é a maior dentre todas.